---
name: 'Generate GH Auth Token'
description: 'Generate GH Auth Token Action'
inputs:
  github_app_pem_file:
    description: 'github app pem file'
    required: true
  github_app_installation_id:
    description: 'github app installation id'
    required: true
  github_app_id:
    description: 'github app id'
    required: false
    default: '6'
outputs:
  github_token:
    description: 'the generated token.'
    value: ${{ steps.github_credentials.outputs.GITHUB_TOKEN }}
runs:
  using: 'composite'
  steps:
    - name: Setup GITHUB Credentials
      id: github_credentials
      shell: bash
      run: |
        echo GITHUB_TOKEN=$(python ${{ github.action_path }}/encode_jwt.py --private-key "${{ inputs.github_app_pem_file }}" --installation-id "${{ inputs.github_app_installation_id }}" --enterprise-url "${{ github.server_url }}" --app-id "${{ inputs.github_app_id }}") >> $GITHUB_OUTPUT
